"""empty message

Revision ID: 1af9f3afc091
Revises: 4ff6b848440c
Create Date: 2025-06-13 14:33:17.424370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af9f3afc091'
down_revision = '4ff6b848440c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_comment_delivery_details', sa.Column('comment', sa.String(length=550), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('add_comment_delivery_details', 'comment')
    # ### end Alembic commands ###
