"""empty message

Revision ID: 251cfb16910c
Revises: 393909e87a5d
Create Date: 2025-06-12 16:19:22.234153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251cfb16910c'
down_revision = '393909e87a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=150), nullable=True),
    sa.Column('start_time', sa.String(length=150), nullable=True),
    sa.Column('end_time', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=350), nullable=True),
    sa.Column('lat', sa.String(length=50), nullable=True),
    sa.Column('long', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_day', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_details')
    # ### end Alembic commands ###
