"""empty message

Revision ID: 30f8589a4507
Revises: 251cfb16910c
Create Date: 2025-06-12 16:21:48.743190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f8589a4507'
down_revision = '251cfb16910c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_details', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
