"""empty message

Revision ID: 393909e87a5d
Revises: b657461e14b5
Create Date: 2025-06-11 19:24:16.783984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393909e87a5d'
down_revision = 'b657461e14b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
