"""empty message

Revision ID: 4b6b103721c0
Revises: 30f8589a4507
Create Date: 2025-06-13 03:58:54.165149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6b103721c0'
down_revision = '30f8589a4507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_details', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
