"""empty message

Revision ID: 4ff6b848440c
Revises: 90811655e772
Create Date: 2025-06-13 14:32:54.295321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ff6b848440c'
down_revision = '90811655e772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('add_comment_delivery_details', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_comment_delivery_details', sa.Column('comment', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
