"""empty message

Revision ID: 90811655e772
Revises: b907ec40937c
Create Date: 2025-06-13 13:51:59.208729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90811655e772'
down_revision = 'b907ec40937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_delivery_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'add_comment_delivery_details', ['comment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_delivery_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
