"""empty message

Revision ID: b657461e14b5
Revises: 
Create Date: 2025-06-11 18:41:43.075948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b657461e14b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=150), nullable=True),
    sa.Column('lastname', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('delete_reason', sa.String(length=1000), nullable=True),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.Column('is_block', sa.Boolean(), nullable=True),
    sa.Column('device_token', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('is_notification', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('faqs')
    op.drop_table('cms')
    op.drop_table('admin')
    # ### end Alembic commands ###
