"""empty message

Revision ID: b907ec40937c
Revises: 6698a2f49b81
Create Date: 2025-06-13 13:44:35.699609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b907ec40937c'
down_revision = '6698a2f49b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_comment_delivery_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('image_delivery_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_delivery_details', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    with op.batch_alter_table('add_comment_delivery_details', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
